/**
 * PARTYDECK Master Game Registry
 * Full schema required by hub-ui.js (openGameModal, card renderer, filters)
 */
const PARTY_GAMES = [
  {
    id: "tele-sketch",
    title: "Tele-Sketch",
    icon: "pencil",
    tagline: "Telephone, but everyone draws.",
    description: "Pass the device around as prompts alternate between drawing and guessing, then watch the hilarious chain unfold in the finale slideshow.",
    tags: ["Creative", "Party", "Drawing"],
    category: "creative",
    minPlayers: 4,
    maxPlayers: 12,
    estimatedTime: "15-25 min",
    drinkingMode: false,
    entryPath: "games/tele-sketch/index.html"
  },
  {
    id: "infiltrator",
    title: "The Infiltrator",
    icon: "spy",
    tagline: "Find the spy before time runs out.",
    description: "Everyone gets a secret location and role except the Infiltrator. Grill each other with questions, then vote out the spy or watch them steal the win.",
    tags: ["Deduction", "Social", "Bluffing"],
    category: "deduction",
    minPlayers: 3,
    maxPlayers: 14,
    estimatedTime: "10-15 min",
    drinkingMode: false,
    entryPath: "games/infiltrator/index.html"
  },
  {
    id: "kings-chalice",
    title: "King's Chalice",
    icon: "crown",
    tagline: "Ring of Fire, reimagined.",
    description: "Draw cards to trigger rules, fill the Chalice, and pray you don't draw the 4th King.",
    tags: ["Drinking", "Cards", "Party"],
    category: "drinking",
    minPlayers: 2,
    maxPlayers: 16,
    estimatedTime: "20-40 min",
    drinkingMode: true,
    entryPath: "games/kings-chalice/index.html"
  },
  {
    id: "social-roulette",
    title: "Social Roulette",
    icon: "flame",
    tagline: "Spin the wheel of chaos.",
    description: "A spinning wheel dishes out icebreakers, dares, and hot questions with your friends' names injected right into the prompt.",
    tags: ["Party", "Icebreaker", "Random"],
    category: "social",
    minPlayers: 2,
    maxPlayers: 16,
    estimatedTime: "10-30 min",
    drinkingMode: true,
    entryPath: "games/social-roulette/index.html"
  },
  {
    id: "most-likely-to",
    title: "Most Likely To...",
    icon: "vote",
    tagline: "Who's really the problem here?",
    description: "Vote in secret or live on who's most likely to do something ridiculous, then watch the results roll in.",
    tags: ["Social", "Voting", "Party"],
    category: "social",
    minPlayers: 3,
    maxPlayers: 12,
    estimatedTime: "10-20 min",
    drinkingMode: true,
    entryPath: "games/most-likely-to/index.html"
  },
  {
    id: "chameleon-word",
    title: "Chameleon Word",
    icon: "eye",
    tagline: "One of you doesn't know the word.",
    description: "A secret grid holds a hidden word. Give one-word clues, catch the Chameleon, or let them guess their way to victory.",
    tags: ["Deduction", "Word Game", "Social"],
    category: "deduction",
    minPlayers: 3,
    maxPlayers: 10,
    estimatedTime: "10-15 min",
    drinkingMode: false,
    entryPath: "games/chameleon-word/index.html"
  },
  {
    id: "liars-dice",
    title: "Liar's Dice",
    icon: "dice",
    tagline: "Trust no one's cup.",
    description: "Bid on the dice hidden under everyone's cup, bluff your way through, and call out liars before it's too late.",
    tags: ["Bluffing", "Dice", "Strategy"],
    category: "bluffing",
    minPlayers: 2,
    maxPlayers: 6,
    estimatedTime: "15-25 min",
    drinkingMode: false,
    entryPath: "games/liars-dice/index.html"
  },
  {
    id: "rapid-buzzer",
    title: "Rapid Buzzer",
    icon: "bomb",
    tagline: "Don't get caught holding it.",
    description: "Pass the device around your team, naming anything you can before a randomized fuse detonates in your hands.",
    tags: ["Action", "Team", "Fast-Paced"],
    category: "action",
    minPlayers: 4,
    maxPlayers: 12,
    estimatedTime: "10-20 min",
    drinkingMode: false,
    entryPath: "games/rapid-buzzer/index.html"
  },
  {
    id: "five-second-rule",
    title: "5-Second Rule",
    icon: "clock",
    tagline: "Think fast or lose.",
    description: "Name three things in a category before the ring runs out — easier said than done under pressure.",
    tags: ["Fast-Paced", "Trivia", "Party"],
    category: "action",
    minPlayers: 2,
    maxPlayers: 10,
    estimatedTime: "10-15 min",
    drinkingMode: false,
    entryPath: "games/five-second-rule/index.html"
  },
  {
    id: "do-or-drink",
    title: "Do or Drink",
    icon: "flame",
    tagline: "Dare or pay the price.",
    description: "Tiered dares worth points versus a configurable penalty — sips, shots, push-ups, or truths, your call.",
    tags: ["Drinking", "Dares", "Party"],
    category: "drinking",
    minPlayers: 2,
    maxPlayers: 12,
    estimatedTime: "15-30 min",
    drinkingMode: true,
    entryPath: "games/do-or-drink/index.html"
  },
  {
    id: "wits-wagers",
    title: "Wits & Wagers",
    icon: "coin",
    tagline: "You don't need to know — just bet smart.",
    description: "Guess numeric trivia answers, then wager chips on whose guess is closest without going over.",
    tags: ["Trivia", "Betting", "Strategy"],
    category: "trivia",
    minPlayers: 3,
    maxPlayers: 10,
    estimatedTime: "15-25 min",
    drinkingMode: false,
    entryPath: "games/wits-wagers/index.html"
  },
  {
    id: "medusa-eye",
    title: "Medusa's Eye",
    icon: "eye",
    tagline: "Don't get caught looking.",
    description: "Eyes down, then look up and lock eyes with a target. Mutual eye contact turns you both to stone.",
    tags: ["Action", "Social", "Elimination"],
    category: "action",
    minPlayers: 3,
    maxPlayers: 10,
    estimatedTime: "10-15 min",
    drinkingMode: false,
    entryPath: "games/medusa-eye/index.html"
  },
  {
    id: "fake-artist",
    title: "A Fake Artist Goes to New York",
    icon: "brush",
    tagline: "One of you can't actually draw the word.",
    description: "Everyone knows the secret word except the Fake Artist. Draw one stroke per turn on a shared canvas and hunt the impostor.",
    tags: ["Creative", "Deduction", "Drawing"],
    category: "creative",
    minPlayers: 4,
    maxPlayers: 10,
    estimatedTime: "15-25 min",
    drinkingMode: false,
    entryPath: "games/fake-artist/index.html"
  },
  {
    id: "sound-bites",
    title: "Sound Bites",
    icon: "phone",
    tagline: "Forehead charades, tilt-controlled.",
    description: "Hold the phone to your forehead and tilt to mark correct guesses or pass, racing the clock as your team shouts clues.",
    tags: ["Action", "Charades", "Fast-Paced"],
    category: "action",
    minPlayers: 2,
    maxPlayers: 12,
    estimatedTime: "10-20 min",
    drinkingMode: false,
    entryPath: "games/sound-bites/index.html"
  },
  {
    id: "resistance-cell",
    title: "Resistance: Mini-Cell",
    icon: "cell",
    tagline: "Trust is the real weapon.",
    description: "Secret Spies sabotage missions while Resistance members try to root them out across 5 tense rounds of team votes.",
    tags: ["Deduction", "Strategy", "Team"],
    category: "deduction",
    minPlayers: 5,
    maxPlayers: 10,
    estimatedTime: "20-30 min",
    drinkingMode: false,
    entryPath: "games/resistance-cell/index.html"
  },
  {
    id: "one-night-wolf",
    title: "One Night Werewolf",
    icon: "moon",
    tagline: "One night. One chance to lie.",
    description: "Secret roles, a night phase guided by narration, and a single dawn debate before the village votes someone out.",
    tags: ["Deduction", "Social", "Bluffing"],
    category: "deduction",
    minPlayers: 3,
    maxPlayers: 10,
    estimatedTime: "15-20 min",
    drinkingMode: false,
    entryPath: "games/one-night-wolf/index.html"
  },
  {
    id: "decrypto-blitz",
    title: "Decrypto Blitz",
    icon: "lock",
    tagline: "Speak in code, or get intercepted.",
    description: "Two teams race to transmit secret 3-digit codes using clever clues while trying to intercept the other side's transmissions.",
    tags: ["Strategy", "Team", "Word Game"],
    category: "deduction",
    minPlayers: 4,
    maxPlayers: 10,
    estimatedTime: "20-30 min",
    drinkingMode: false,
    entryPath: "games/decrypto-blitz/index.html"
  },
  {
    id: "coup-pocket",
    title: "Coup: Pocket Edition",
    icon: "crown",
    tagline: "Bluff your way to the throne.",
    description: "Bluff, tax, assassinate, and steal your way to being the last influence standing in the court.",
    tags: ["Bluffing", "Strategy", "Cards"],
    category: "bluffing",
    minPlayers: 2,
    maxPlayers: 6,
    estimatedTime: "15-30 min",
    drinkingMode: false,
    entryPath: "games/coup-pocket/index.html"
  },
  {
    id: "two-rooms-lite",
    title: "Two Rooms & A Boom Lite",
    icon: "split",
    tagline: "Keep the bomb away from the President.",
    description: "Split into two rooms, trade hostages across timed rounds, and hope the Bomber and President never end up together.",
    tags: ["Social", "Team", "Strategy"],
    category: "social",
    minPlayers: 6,
    maxPlayers: 12,
    estimatedTime: "20-30 min",
    drinkingMode: false,
    entryPath: "games/two-rooms-lite/index.html"
  },
  {
    id: "skull-digital",
    title: "Skull: Digital Bluff",
    icon: "skull",
    tagline: "Bid big, flip carefully.",
    description: "Play Roses and Skulls face down, then bid on how many cards you can flip without hitting a single Skull.",
    tags: ["Bluffing", "Cards", "Strategy"],
    category: "bluffing",
    minPlayers: 3,
    maxPlayers: 6,
    estimatedTime: "15-25 min",
    drinkingMode: false,
    entryPath: "games/skull-digital/index.html"
  }
];