const PARTY_GAMES = [
  { id: "telestrations",     title: "Tele-Sketch",                  category: "creative",  minPlayers: 4, maxPlayers: 12, entryPath: "games/telestrations/index.html" },
  { id: "infiltrator",       title: "The Infiltrator",              category: "deduction", minPlayers: 3, maxPlayers: 14, entryPath: "games/infiltrator/index.html" },
  { id: "kings-chalice",     title: "King's Chalice",               category: "drinking",  minPlayers: 2, maxPlayers: 16, entryPath: "games/kings-chalice/index.html" },
  { id: "social-roulette",   title: "Social Roulette",              category: "drinking",  minPlayers: 2, maxPlayers: 16, entryPath: "games/social-roulette/index.html" },
  { id: "most-likely-to",    title: "Most Likely To...",            category: "social",    minPlayers: 3, maxPlayers: 12, entryPath: "games/most-likely-to/index.html" },
  { id: "chameleon-word",    title: "Chameleon Word",               category: "deduction", minPlayers: 3, maxPlayers: 10, entryPath: "games/chameleon-word/index.html" },
  { id: "liars-dice",        title: "Liar's Dice",                  category: "bluffing",  minPlayers: 2, maxPlayers: 6,  entryPath: "games/liars-dice/index.html" },
  { id: "rapid-buzzer",      title: "Rapid Buzzer",                 category: "action",    minPlayers: 4, maxPlayers: 12, entryPath: "games/rapid-buzzer/index.html" },
  { id: "five-second-rule",  title: "5-Second Rule",                category: "action",    minPlayers: 2, maxPlayers: 10, entryPath: "games/five-second-rule/index.html" },
  { id: "do-or-drink",       title: "Do or Drink",                  category: "drinking",  minPlayers: 2, maxPlayers: 12, entryPath: "games/do-or-drink/index.html" },
  { id: "wits-wagers",       title: "Wits & Wagers",                category: "trivia",    minPlayers: 3, maxPlayers: 10, entryPath: "games/wits-wagers/index.html" },
  { id: "medusa-eye",        title: "Medusa's Eye",                 category: "action",    minPlayers: 3, maxPlayers: 10, entryPath: "games/medusa-eye/index.html" },
  { id: "fake-artist",       title: "A Fake Artist in New York",    category: "creative",  minPlayers: 4, maxPlayers: 10, entryPath: "games/fake-artist/index.html" },
  { id: "sound-bites",       title: "Sound Bites",                  category: "action",    minPlayers: 2, maxPlayers: 12, entryPath: "games/sound-bites/index.html" },
  { id: "resistance-cell",   title: "Resistance: Mini-Cell",        category: "deduction", minPlayers: 5, maxPlayers: 10, entryPath: "games/resistance-cell/index.html" },
  { id: "one-night-wolf",    title: "One Night Werewolf",           category: "deduction", minPlayers: 3, maxPlayers: 10, entryPath: "games/one-night-wolf/index.html" },
  { id: "decrypto-blitz",    title: "Decrypto Blitz",               category: "deduction", minPlayers: 4, maxPlayers: 10, entryPath: "games/decrypto-blitz/index.html" },
  { id: "coup-pocket",       title: "Coup: Pocket Edition",         category: "bluffing",  minPlayers: 2, maxPlayers: 6,  entryPath: "games/coup-pocket/index.html" },
  { id: "two-rooms-lite",    title: "Two Rooms & A Boom Lite",      category: "social",    minPlayers: 6, maxPlayers: 12, entryPath: "games/two-rooms-lite/index.html" },
  { id: "skull-digital",     title: "Skull: Digital Bluff",         category: "bluffing",  minPlayers: 3, maxPlayers: 6,  entryPath: "games/skull-digital/index.html" }
];