/**
 * PARTYDECK Master Game Catalog Configuration
 * Complete registry of 20 games ready for plug-and-play expansion.
 */
const PARTY_GAMES = [
  {
    id: "tele-sketch",
    title: "Tele-Sketch",
    tagline: "Draw, Guess, Laugh, Repeat",
    category: "creative",
    tags: ["Drawing", "Pass & Play", "Hilarious"],
    minPlayers: 4,
    maxPlayers: 12,
    drinkingMode: false,
    estimatedTime: "15-25 min",
    icon: "🎨",
    entryPath: "games/tele-sketch/index.html",
    description: "The classic telephone game turned visual. Draw secret prompts, pass the phone, guess what you see, and watch the chain turn into absurd comedy."
  },
  {
    id: "infiltrator",
    title: "The Infiltrator",
    tagline: "Find the Impostor in the Room",
    category: "deduction",
    tags: ["Bluffing", "Secret Roles", "Pass & Play"],
    minPlayers: 3,
    maxPlayers: 10,
    drinkingMode: true,
    estimatedTime: "10-15 min",
    icon: "🕵️",
    entryPath: "games/infiltrator/index.html",
    description: "Everyone gets the secret location except the Infiltrator. Ask clever questions without giving the location away!"
  },
  {
    id: "kings-chalice",
    title: "King's Chalice",
    tagline: "The Ultimate Digital Drinking Deck",
    category: "drinking",
    tags: ["Party Classic", "Card Game", "Custom Rules"],
    minPlayers: 2,
    maxPlayers: 12,
    drinkingMode: true,
    estimatedTime: "20-40 min",
    icon: "🍻",
    entryPath: "games/kings-chalice/index.html",
    description: "Draw cards from the ring of fire. Includes interactive mini-games for Heaven, Categories, and Thumb Master."
  },
  {
    id: "social-roulette",
    title: "Social Roulette",
    tagline: "Dynamic Prompts & Group Dares",
    category: "drinking",
    tags: ["Spicy", "Fast-Paced", "Icebreaker"],
    minPlayers: 3,
    maxPlayers: 15,
    drinkingMode: true,
    estimatedTime: "15-30 min",
    icon: "🔥",
    entryPath: "games/social-roulette/index.html",
    description: "An algorithmic party companion that injects player names into wild prompts, spicy questions, and party dares."
  },
  {
    id: "chameleon-word",
    title: "Chameleon Word",
    tagline: "Blend In, Don't Get Caught",
    category: "deduction",
    tags: ["Word Game", "Bluffing", "Pass & Play"],
    minPlayers: 3,
    maxPlayers: 8,
    drinkingMode: false,
    estimatedTime: "10 min",
    icon: "🦎",
    entryPath: "games/chameleon-word/index.html",
    description: "Everyone knows the secret word on the coordinate grid except the Chameleon. Say single-word clues and hunt the impostor."
  },
  {
    id: "most-likely-to",
    title: "Most Likely To...",
    tagline: "Expose Your Friends' Secrets",
    category: "social",
    tags: ["Voting", "Hot Seat", "Spicy"],
    minPlayers: 3,
    maxPlayers: 12,
    drinkingMode: true,
    estimatedTime: "15-20 min",
    icon: "🗳️",
    entryPath: "games/most-likely-to/index.html",
    description: "Vote on who in the room is most likely to end up in absurd situations. Real-time voting reveals the truth."
  },
  {
    id: "liars-dice",
    title: "Liar's Dice",
    tagline: "Bluff, Bid, and Call the Bluff",
    category: "bluffing",
    tags: ["Dice", "Strategy", "Pass & Hide"],
    minPlayers: 2,
    maxPlayers: 6,
    drinkingMode: false,
    estimatedTime: "15-25 min",
    icon: "🎲",
    entryPath: "games/liars-dice/index.html",
    description: "Roll secret virtual dice under your cup, bid on the total number of dice in the room, and call your friends liars."
  },
  {
    id: "rapid-buzzer",
    title: "Rapid Buzzer",
    tagline: "Pass the Ticking Bomb!",
    category: "action",
    tags: ["Word Guess", "Hot Potato", "Fast"],
    minPlayers: 4,
    maxPlayers: 12,
    drinkingMode: true,
    estimatedTime: "10-15 min",
    icon: "💣",
    entryPath: "games/rapid-buzzer/index.html",
    description: "Get your team to guess the clue and pass the phone before the unpredictable ticking countdown explodes."
  },
  {
    id: "sound-bites",
    title: "Sound Bites (Heads Up)",
    tagline: "Forehead Charades & Clues",
    category: "action",
    tags: ["Motion Tilt", "Charades", "High Energy"],
    minPlayers: 2,
    maxPlayers: 10,
    drinkingMode: false,
    estimatedTime: "5-15 min",
    icon: "📱",
    entryPath: "games/sound-bites/index.html",
    description: "Hold the phone to your forehead. Guess the word from your friends' clues and tilt down for correct or up to pass."
  },
  {
    id: "fake-artist",
    title: "Fake Artist in NY",
    tagline: "One Shared Masterpiece, One Fake",
    category: "creative",
    tags: ["Drawing", "Social Deduction", "Pass & Play"],
    minPlayers: 4,
    maxPlayers: 10,
    drinkingMode: false,
    estimatedTime: "15 min",
    icon: "🖌️",
    entryPath: "games/fake-artist/index.html",
    description: "Everyone draws one single continuous line on the same canvas. The Fake Artist has no idea what is being drawn!"
  },
  {
    id: "resistance-cell",
    title: "Resistance: Mini-Cell",
    tagline: "Lead Missions or Sabotage from Within",
    category: "deduction",
    tags: ["Secret Traitor", "Strategy", "No Elimination"],
    minPlayers: 5,
    maxPlayers: 10,
    drinkingMode: false,
    estimatedTime: "20-30 min",
    icon: "🛡️",
    entryPath: "games/resistance-cell/index.html",
    description: "Send teams on secret missions. Spies try to covertly fail them while operatives try to pass them."
  },
  {
    id: "one-night-wolf",
    title: "One Night Werewolf",
    tagline: "One Night. One Vote. Who Survives?",
    category: "deduction",
    tags: ["Hidden Role", "Night Phase", "Voice Narrator"],
    minPlayers: 3,
    maxPlayers: 10,
    drinkingMode: false,
    estimatedTime: "10 min",
    icon: "🐺",
    entryPath: "games/one-night-wolf/index.html",
    description: "Get secret night roles. Follow the digital voice narration, then wake up and vote to eliminate the werewolf."
  },
  {
    id: "do-or-drink",
    title: "Do or Drink: Ultimate",
    tagline: "Do the Extreme Dare or Chug",
    category: "drinking",
    tags: ["Wild Dares", "Party Classic", "Challenges"],
    minPlayers: 2,
    maxPlayers: 10,
    drinkingMode: true,
    estimatedTime: "20-40 min",
    icon: "🍹",
    entryPath: "games/do-or-drink/index.html",
    description: "Hilarious and outrageous dares. Complete the challenge to earn points or take your punishment sips."
  },
  {
    id: "wits-wagers",
    title: "Wits & Wagers: Micro",
    tagline: "Bet on the Best Guess",
    category: "trivia",
    tags: ["Betting", "Numbers", "Shared Board"],
    minPlayers: 3,
    maxPlayers: 10,
    drinkingMode: false,
    estimatedTime: "15-25 min",
    icon: "🏆",
    entryPath: "games/wits-wagers/index.html",
    description: "You don't need to know the exact answer. Guess any number, then bet your chips on who is closest without going over."
  },
  {
    id: "decrypto-blitz",
    title: "Decrypto Blitz",
    tagline: "Crack the Enemy Team's Codes",
    category: "deduction",
    tags: ["Team vs Team", "Codes", "Wordplay"],
    minPlayers: 4,
    maxPlayers: 8,
    drinkingMode: false,
    estimatedTime: "20-35 min",
    icon: "🔐",
    entryPath: "games/decrypto-blitz/index.html",
    description: "Transmit 3-digit secret codes to your teammates without letting the opposing team intercept the meaning."
  },
  {
    id: "coup-pocket",
    title: "Coup: Pocket Edition",
    tagline: "Bribe, Bluff, and Eliminate",
    category: "bluffing",
    tags: ["Influence", "Deception", "Fast Strategy"],
    minPlayers: 2,
    maxPlayers: 6,
    drinkingMode: false,
    estimatedTime: "15 min",
    icon: "👑",
    entryPath: "games/coup-pocket/index.html",
    description: "Claim any role you want to gain wealth and eliminate rivals. Just ensure nobody calls your bluff!"
  },
  {
    id: "five-second-rule",
    title: "5-Second Rule",
    tagline: "3 Things in 5 Seconds. GO!",
    category: "action",
    tags: ["High Pressure", "Trivia", "Fast Pass"],
    minPlayers: 3,
    maxPlayers: 10,
    drinkingMode: true,
    estimatedTime: "10-20 min",
    icon: "⏱️",
    entryPath: "games/five-second-rule/index.html",
    description: "Name 3 items in your category before the 5-second countdown finishes. Quick thinking guaranteed to cause laughter."
  },
  {
    id: "two-rooms-lite",
    title: "Two Rooms & A Boom Lite",
    tagline: "Separate Rooms, Secret Agendas",
    category: "deduction",
    tags: ["Large Group", "Hostage Swap", "Split Room"],
    minPlayers: 6,
    maxPlayers: 16,
    drinkingMode: false,
    estimatedTime: "15-20 min",
    icon: "⚡",
    entryPath: "games/two-rooms-lite/index.html",
    description: "Split your party into two rooms. Blue protects the President; Red brings the Bomber. Trade hostages before time expires."
  },
  {
    id: "skull-digital",
    title: "Skull: Digital Bluff",
    tagline: "Roses Smell Sweet. Skulls Kill.",
    category: "bluffing",
    tags: ["Mind Games", "Risk & Reward", "Pass & Play"],
    minPlayers: 3,
    maxPlayers: 6,
    drinkingMode: false,
    estimatedTime: "15-20 min",
    icon: "💀",
    entryPath: "games/skull-digital/index.html",
    description: "Play cards face down. Bid on how many roses you can turn over across the room without revealing a fatal skull."
  },
  {
    id: "medusa-eye",
    title: "Medusa: Eye Contact",
    tagline: "Look Up and Scream!",
    category: "action",
    tags: ["Reaction", "Tabletop Radial", "Chaos"],
    minPlayers: 4,
    maxPlayers: 12,
    drinkingMode: true,
    estimatedTime: "5-10 min",
    icon: "👁️",
    entryPath: "games/medusa-eye/index.html",
    description: "Put the phone in the middle of the table. Look up on 3! If you make eye contact with someone looking back, tap fast!"
  }
];